### ISSUE TITLE
Failed to read host ComfyUI-BjornulfNodes\ollama_ip.txt

### ISSUE THREAD

**Issue by emourdavid** [justUmen/Bjornulf_custom_nodes#8]
Looking for file at: xxx\ComfyUI\custom_nodes\ComfyUI-BjornulfNodes\ollama_ip.txt
Failed to read host from xxx\ComfyUI\custom_nodes\ComfyUI-BjornulfNodes\ollama_ip.txt: [Errno 2] 

I got this warning after upgrade.

**Comment by plaidam** [comment]
same error.

**Comment by justUmen** [comment]
Hi there, thx for the report !!
(My upgrade or Comfy upgrade ? I didn't change this since 0.44, which was Sep 25)

So you are both on windows and you have ollama installed ? (I've never tested this node on windows)
This txt file shouldn't be mandatory, do you use it ?

Can you can try to create this file and put this line inside ?
http://127.0.0.1:11434
Or this one ?
http://0.0.0.0:11434

Quote from my README (might rephrase that)
`⚠️ You can create a file called ollama_ip.txt in my comfyui custom node folder if you have a special IP for your ollama server, mine is : http://192.168.1.37:11434`

**Comment by justUmen** [comment]
0.51 should fix it automatically for now.
Let me know if it's good now. THX !!!
